-- Authored help guides (generated by `fierylib seed help --emit-sql`).
-- Source: fierylib/data/help/*.md. Do not edit by hand; edit the markdown
-- and regenerate.
-- Idempotent: matches on the primary keyword ("HelpEntry" has no unique key),
-- overwriting a legacy entry with the same primary keyword; re-runs change nothing
-- except updated_at.

-- bank: The Bank
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'bank' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'bank' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['bank', 'banking', 'atm', 'deposit', 'withdraw', 'balance', 'bal']::text[],
      'The Bank',
      $help$The bank keeps your coin separate from the coin you carry. Bankers are
NPCs found in town banks.

  balance          (or bal) show your bank balance and the coin you carry.
                   Works anywhere.
  wealth           show only the coin you carry.
  deposit 1000     move 1000 copper from your pocket into the bank.
  withdraw 500     take 500 copper back out.

  deposit and withdraw need a banker in the room, and the amount is a
  whole number of copper pieces: 1000 copper is 1 platinum, so
  "deposit 1000" banks one platinum. (Writing "deposit 400 copper" is
  not understood; just give the number.)

CHANGING COINS
  "exchange {amount} {from} {to}" swaps coins at a banker. The coin types
  are copper, silver, gold and platinum (c, s, g and p also work).

    exchange 50 silver gold    turn 50 silver into 5 gold

  Rates are 10 copper = 1 silver, 10 silver = 1 gold, 10 gold = 1
  platinum. Your total wealth doesn't change; anything too small to fill
  a whole coin of the new type comes back to you as change.

ACCOUNT BANK AND CHEST
  Characters on the same website account can share money and items:
    account_balance                  the shared pool (abal)
    account_deposit {copper}         move copper from your character's bank
                                     balance into the shared pool
    account_withdraw {copper}        move it back
    chest                            list the shared item chest
    chest_deposit {item}             store an item (not soulbound or
                                     no-drop items)
    chest_withdraw {slot}            take an item back out

See also: SHOPS, MAIL.$help$,
      0,
      'guide',
      'balance | deposit {copper} | withdraw {copper} | exchange {amount} {from} {to}',
      'data/help/bank.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['bank', 'banking', 'atm', 'deposit', 'withdraw', 'balance', 'bal']::text[],
      title = 'The Bank',
      content = $help$The bank keeps your coin separate from the coin you carry. Bankers are
NPCs found in town banks.

  balance          (or bal) show your bank balance and the coin you carry.
                   Works anywhere.
  wealth           show only the coin you carry.
  deposit 1000     move 1000 copper from your pocket into the bank.
  withdraw 500     take 500 copper back out.

  deposit and withdraw need a banker in the room, and the amount is a
  whole number of copper pieces: 1000 copper is 1 platinum, so
  "deposit 1000" banks one platinum. (Writing "deposit 400 copper" is
  not understood; just give the number.)

CHANGING COINS
  "exchange {amount} {from} {to}" swaps coins at a banker. The coin types
  are copper, silver, gold and platinum (c, s, g and p also work).

    exchange 50 silver gold    turn 50 silver into 5 gold

  Rates are 10 copper = 1 silver, 10 silver = 1 gold, 10 gold = 1
  platinum. Your total wealth doesn't change; anything too small to fill
  a whole coin of the new type comes back to you as change.

ACCOUNT BANK AND CHEST
  Characters on the same website account can share money and items:
    account_balance                  the shared pool (abal)
    account_deposit {copper}         move copper from your character's bank
                                     balance into the shared pool
    account_withdraw {copper}        move it back
    chest                            list the shared item chest
    chest_deposit {item}             store an item (not soulbound or
                                     no-drop items)
    chest_withdraw {slot}            take an item back out

See also: SHOPS, MAIL.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'balance | deposit {copper} | withdraw {copper} | exchange {amount} {from} {to}',
      source_file = 'data/help/bank.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- boards: Message Boards
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'boards' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'boards' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['boards', 'board', 'message-boards', 'bulletin-boards', 'post', 'editpost', 'delpost']::text[],
      'Message Boards',
      $help$Message boards are where players leave public notes for each other. Boards
are physical: stand in the room that has the board to use it. (Builders and
immortals can reach any board from anywhere.)

READING
  look board        list the messages on the board in this room
  board             same thing; "board list" also works
  board mortal 3    list a board by its alias, or read message 3 on it
  read 3            read message 3 on the board in this room
  boards            see which boards exist

  Messages are listed newest first, with sticky messages at the top.

POSTING
  post              start a new post on the board in this room

  The first line you type is the subject. Everything after it is the body.
  Type these on a line by themselves:
    .preview   show your draft
    .send      post it
    .clear     wipe the draft and start over
    .abort     throw the draft away
  Locked boards refuse new posts.

EDITING AND DELETING
  editpost mortal 3   reopen your own post 3 with its subject and body
                      loaded. Type more lines to add to it, or .clear to
                      rewrite it, then .send.
  delpost mortal 3    delete your own post 3.

  You can only edit or delete your own posts. Staff can edit or delete
  anyone's.

See also: MAIL (private messages), CHANNELS.$help$,
      0,
      'guide',
      'board [alias] [#] | post | editpost {alias} {#} | delpost {alias} {#}',
      'data/help/boards.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['boards', 'board', 'message-boards', 'bulletin-boards', 'post', 'editpost', 'delpost']::text[],
      title = 'Message Boards',
      content = $help$Message boards are where players leave public notes for each other. Boards
are physical: stand in the room that has the board to use it. (Builders and
immortals can reach any board from anywhere.)

READING
  look board        list the messages on the board in this room
  board             same thing; "board list" also works
  board mortal 3    list a board by its alias, or read message 3 on it
  read 3            read message 3 on the board in this room
  boards            see which boards exist

  Messages are listed newest first, with sticky messages at the top.

POSTING
  post              start a new post on the board in this room

  The first line you type is the subject. Everything after it is the body.
  Type these on a line by themselves:
    .preview   show your draft
    .send      post it
    .clear     wipe the draft and start over
    .abort     throw the draft away
  Locked boards refuse new posts.

EDITING AND DELETING
  editpost mortal 3   reopen your own post 3 with its subject and body
                      loaded. Type more lines to add to it, or .clear to
                      rewrite it, then .send.
  delpost mortal 3    delete your own post 3.

  You can only edit or delete your own posts. Staff can edit or delete
  anyone's.

See also: MAIL (private messages), CHANNELS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'board [alias] [#] | post | editpost {alias} {#} | delpost {alias} {#}',
      source_file = 'data/help/boards.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- communication: Channels and Chat
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'communication' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'communication' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['communication', 'channels', 'channel', 'chat', 'chatting', 'talking']::text[],
      'Channels and Chat',
      $help$Ways to talk, from closest to furthest.

IN THE ROOM
  say hello there          speak to the room (also ')
  whisper Aria meet me     only Aria hears the words; others see you whisper
  ask {mob} {topic}        ask an NPC about something (starts quests)
  emote waves hello        everyone sees "Strider waves hello." (also :)
  socials                  list the premade social commands (smile, bow...)

PRIVATE
  tell Aria hello          message one player anywhere (also t)
  reply thanks             answer whoever tell'd you last (also r)
  lasttells                your recent tells

GROUP AND CLAN
  gsay {message}           your group     (also gtell, gt)
  ctell {message}          your clan      (also ct)

WORLD CHANNELS
  gossip {message}         everyone online (also / and .). Hints about the
                           world are welcome; please keep quest answers out.
  shout {message}          to everyone (also sh)
  music {message}          song lyrics and similar
  qsay {message}           the quest channel, for questers to coordinate
  lastgossips [n]  lastshouts [n]    replay recent lines (up to 50)

CONTROLS
  deaf                     stop hearing gossip and shout; type again to hear
  notell                   refuse tells; type again to allow them
  afk                      mark yourself away; type again to return
  ignore Bob               block Bob's tells and channel messages
  ignore -Bob              stop ignoring Bob (or: unignore Bob)
  ignore clear             empty the list
  The ignore list lasts for the current session only.

See also: GROUPS, CLANS, MAIL, BOARDS.$help$,
      0,
      'guide',
      'say | tell {player} | gossip | gsay | ctell | shout | emote',
      'data/help/channels.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['communication', 'channels', 'channel', 'chat', 'chatting', 'talking']::text[],
      title = 'Channels and Chat',
      content = $help$Ways to talk, from closest to furthest.

IN THE ROOM
  say hello there          speak to the room (also ')
  whisper Aria meet me     only Aria hears the words; others see you whisper
  ask {mob} {topic}        ask an NPC about something (starts quests)
  emote waves hello        everyone sees "Strider waves hello." (also :)
  socials                  list the premade social commands (smile, bow...)

PRIVATE
  tell Aria hello          message one player anywhere (also t)
  reply thanks             answer whoever tell'd you last (also r)
  lasttells                your recent tells

GROUP AND CLAN
  gsay {message}           your group     (also gtell, gt)
  ctell {message}          your clan      (also ct)

WORLD CHANNELS
  gossip {message}         everyone online (also / and .). Hints about the
                           world are welcome; please keep quest answers out.
  shout {message}          to everyone (also sh)
  music {message}          song lyrics and similar
  qsay {message}           the quest channel, for questers to coordinate
  lastgossips [n]  lastshouts [n]    replay recent lines (up to 50)

CONTROLS
  deaf                     stop hearing gossip and shout; type again to hear
  notell                   refuse tells; type again to allow them
  afk                      mark yourself away; type again to return
  ignore Bob               block Bob's tells and channel messages
  ignore -Bob              stop ignoring Bob (or: unignore Bob)
  ignore clear             empty the list
  The ignore list lasts for the current session only.

See also: GROUPS, CLANS, MAIL, BOARDS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'say | tell {player} | gossip | gsay | ctell | shout | emote',
      source_file = 'data/help/channels.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- clans: Clans
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'clans' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'clans' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['clans', 'guilds', 'clan-chat']::text[],
      'Clans',
      $help$A clan is a player organisation with its own roster, message of the day and
private chat channel. Clans are created and staffed by the immortals: you
join one when staff assign you to it, and they set your rank (leader,
officer or member). If you want to found or join a clan, ask a god.

COMMANDS
  clan               show your clan's name, abbreviation, message of the
                     day and roster. The roster is sorted leader, officer,
                     member, then by level and name; an asterisk marks
                     members who are online.
  ctell {message}    talk on the clan channel (also "ct"). Every online
                     member hears it.
  clan motd {text}   set the clan's message of the day. Leaders and
                     officers only. "clan motd" with no text clears it.
  clan kick {name}   remove a member from the clan. Leaders only.

  If you aren't in a clan, these commands tell you so.

See also: CHANNELS, GROUPS.$help$,
      0,
      'guide',
      'clan | clan motd {text} | clan kick {player} | ctell {message}',
      'data/help/clans.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['clans', 'guilds', 'clan-chat']::text[],
      title = 'Clans',
      content = $help$A clan is a player organisation with its own roster, message of the day and
private chat channel. Clans are created and staffed by the immortals: you
join one when staff assign you to it, and they set your rank (leader,
officer or member). If you want to found or join a clan, ask a god.

COMMANDS
  clan               show your clan's name, abbreviation, message of the
                     day and roster. The roster is sorted leader, officer,
                     member, then by level and name; an asterisk marks
                     members who are online.
  ctell {message}    talk on the clan channel (also "ct"). Every online
                     member hears it.
  clan motd {text}   set the clan's message of the day. Leaders and
                     officers only. "clan motd" with no text clears it.
  clan kick {name}   remove a member from the clan. Leaders only.

  If you aren't in a clan, these commands tell you so.

See also: CHANNELS, GROUPS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'clan | clan motd {text} | clan kick {player} | ctell {message}',
      source_file = 'data/help/clans.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- consent: Consent, NoSummon and PK
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'consent' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'consent' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['consent', 'no-summon', 'summons', 'summoning', 'consent-and-nosummon']::text[],
      'Consent, NoSummon and PK',
      $help$Three switches control how other players can affect you. Each is a toggle:
type the command once to turn it on and again to turn it off. "flags" lists
the ones you have set.

NOSUMMON
  Someone casting summon on you doesn't move you straight away. You are
  told who wants to summon you and where to, and have 30 seconds to answer:

    accept    go to the caster.
    decline   stay where you are.

  "nosummon" skips the prompt altogether: every summon is refused
  silently and the caster just sees that you are not accepting summons.
  It is handy when you are away from the keyboard. Turn it off again to
  get the prompts back. Staff with the summon permission, and players with
  PK switched on, can't be shielded this way (see PK).

PK
  "pk" marks you as willing to take part in player-versus-player play. While
  it is on, area attacks in your room count you as an enemy and summons reach
  you without a prompt. Leave it off unless you want that.

CONSENT
  "consent" toggles your CONSENT flag, which marks you as trusting other
  players for shared interactions. Today the flag is only recorded; it does
  not change who can loot you. Your own corpse is always safe: only you
  (and staff) can take things from it, whether or not consent is set.

See also: MAGIC, GROUPS, FLAGS.$help$,
      0,
      'guide',
      'consent | nosummon | pk | flags',
      'data/help/consent.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['consent', 'no-summon', 'summons', 'summoning', 'consent-and-nosummon']::text[],
      title = 'Consent, NoSummon and PK',
      content = $help$Three switches control how other players can affect you. Each is a toggle:
type the command once to turn it on and again to turn it off. "flags" lists
the ones you have set.

NOSUMMON
  Someone casting summon on you doesn't move you straight away. You are
  told who wants to summon you and where to, and have 30 seconds to answer:

    accept    go to the caster.
    decline   stay where you are.

  "nosummon" skips the prompt altogether: every summon is refused
  silently and the caster just sees that you are not accepting summons.
  It is handy when you are away from the keyboard. Turn it off again to
  get the prompts back. Staff with the summon permission, and players with
  PK switched on, can't be shielded this way (see PK).

PK
  "pk" marks you as willing to take part in player-versus-player play. While
  it is on, area attacks in your room count you as an enemy and summons reach
  you without a prompt. Leave it off unless you want that.

CONSENT
  "consent" toggles your CONSENT flag, which marks you as trusting other
  players for shared interactions. Today the flag is only recorded; it does
  not change who can loot you. Your own corpse is always safe: only you
  (and staff) can take things from it, whether or not consent is set.

See also: MAGIC, GROUPS, FLAGS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'consent | nosummon | pk | flags',
      source_file = 'data/help/consent.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- group: Groups
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'group' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'group' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['group', 'groups', 'grouping', 'party', 'invite']::text[],
      'Groups',
      $help$Adventuring together is safer and shares the rewards. A group is formed by
following: whoever you follow, directly or through a chain, is your group
leader.

JOINING
  follow Aria        trail Aria; when she moves through an exit, you do too.
  invite Aria        ask Aria to join your group. She answers with
                     "accept" or "decline". Invites expire after 5 minutes.
  accept / decline   answer an invite you have received.
  unfollow           stop following (follow self does the same).

RUNNING THE GROUP
  group              list the leader and members with HP and whether each
                     is in your room.
  dismiss {name}     remove a member who follows you directly.
  group dismiss {name}   the same thing.
  disband            dismiss everyone who follows you.
  order {name|all} {command}   give a command to your mob followers.

TALKING
  gsay {message}     speak to the whole group wherever they are (gtell, gt).
  greport            tell the group your HP and stamina.

SHARING
  Experience from a kill is split evenly between group members who are in
  the same room as the killer.
  split 5000         divide 5000 copper of your own coin between the group
                     members in your room.
  autogold           toggle: coin from your kills is collected for you.
  autosplit          toggle: with autogold on, that coin is split among
                     the group members in your room.
  autoassist         toggle: when the person you follow is attacked in
                     your room, you jump into the fight.
  gretreat           the whole group in your room flees together.

See also: CHANNELS, CONSENT, MAGIC (summon).$help$,
      0,
      'guide',
      'follow {name} | invite {player} | group | gsay {message} | split {copper}',
      'data/help/groups.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['group', 'groups', 'grouping', 'party', 'invite']::text[],
      title = 'Groups',
      content = $help$Adventuring together is safer and shares the rewards. A group is formed by
following: whoever you follow, directly or through a chain, is your group
leader.

JOINING
  follow Aria        trail Aria; when she moves through an exit, you do too.
  invite Aria        ask Aria to join your group. She answers with
                     "accept" or "decline". Invites expire after 5 minutes.
  accept / decline   answer an invite you have received.
  unfollow           stop following (follow self does the same).

RUNNING THE GROUP
  group              list the leader and members with HP and whether each
                     is in your room.
  dismiss {name}     remove a member who follows you directly.
  group dismiss {name}   the same thing.
  disband            dismiss everyone who follows you.
  order {name|all} {command}   give a command to your mob followers.

TALKING
  gsay {message}     speak to the whole group wherever they are (gtell, gt).
  greport            tell the group your HP and stamina.

SHARING
  Experience from a kill is split evenly between group members who are in
  the same room as the killer.
  split 5000         divide 5000 copper of your own coin between the group
                     members in your room.
  autogold           toggle: coin from your kills is collected for you.
  autosplit          toggle: with autogold on, that coin is split among
                     the group members in your room.
  autoassist         toggle: when the person you follow is attacked in
                     your room, you jump into the fight.
  gretreat           the whole group in your room flees together.

See also: CHANNELS, CONSENT, MAGIC (summon).$help$,
      min_level = 0,
      category = 'guide',
      usage = 'follow {name} | invite {player} | group | gsay {message} | split {copper}',
      source_file = 'data/help/groups.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- inn: Inns, Rent and Houses
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'inn' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'inn' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['inn', 'inns', 'housing', 'house', 'houses', 'reception']::text[],
      'Inns, Rent and Houses',
      $help$INNS
  Inns are rooms flagged by the builders. Inside one, "rent" lists the
  rooms on offer and their prices in gold:

    rent               list the rooms and fees
    rent suite         book the room called suite (abbreviations work)

  The fee is flat for each room tier, not per night. The cheapest tier
  books immediately; tiers 2 and 3 ask you to confirm with y or n. Booking
  sets your rest source to the inn: on your next experience gain you get
  the Refreshed regeneration bonus (plus any extras the room carries) and
  the booking is used up. Booking a lower tier after a higher one replaces
  it with no refund. Outside an inn, rent tells you there is nothing to
  rent.

PLAYER HOUSES
  Houses are granted by the builders; if you have none, "house" says so.
  Once you own one:

    house               summary (same as house info)
    house enter         go to your house
    house rooms         list rooms, their contents and capacity
    house guests        list who may visit
    house place {item}  put an item from your inventory in the room
    house take {item}   pick it up again
    house rename 1 Library       rename room 1
    house describe 1 {text}      set room 1's description
    house guest add {name} [place]   allow a visitor ("place" also lets
                                     them put items down)
    house guest remove {name}
    house expand        add a room off the foyer's north exit. It costs
                        copper, more for each room you already have; the
                        game states the price and you need the coin on hand.

  Others enter with "visit {player}", which only works if the owner has
  added them as a guest.

See also: BANK, SHOPS, GETTING-STARTED.$help$,
      0,
      'guide',
      'rent [{room}] | house [info|enter|rooms|guests|expand] | visit {player}',
      'data/help/inn.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['inn', 'inns', 'housing', 'house', 'houses', 'reception']::text[],
      title = 'Inns, Rent and Houses',
      content = $help$INNS
  Inns are rooms flagged by the builders. Inside one, "rent" lists the
  rooms on offer and their prices in gold:

    rent               list the rooms and fees
    rent suite         book the room called suite (abbreviations work)

  The fee is flat for each room tier, not per night. The cheapest tier
  books immediately; tiers 2 and 3 ask you to confirm with y or n. Booking
  sets your rest source to the inn: on your next experience gain you get
  the Refreshed regeneration bonus (plus any extras the room carries) and
  the booking is used up. Booking a lower tier after a higher one replaces
  it with no refund. Outside an inn, rent tells you there is nothing to
  rent.

PLAYER HOUSES
  Houses are granted by the builders; if you have none, "house" says so.
  Once you own one:

    house               summary (same as house info)
    house enter         go to your house
    house rooms         list rooms, their contents and capacity
    house guests        list who may visit
    house place {item}  put an item from your inventory in the room
    house take {item}   pick it up again
    house rename 1 Library       rename room 1
    house describe 1 {text}      set room 1's description
    house guest add {name} [place]   allow a visitor ("place" also lets
                                     them put items down)
    house guest remove {name}
    house expand        add a room off the foyer's north exit. It costs
                        copper, more for each room you already have; the
                        game states the price and you need the coin on hand.

  Others enter with "visit {player}", which only works if the owner has
  added them as a guest.

See also: BANK, SHOPS, GETTING-STARTED.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'rent [{room}] | house [info|enter|rooms|guests|expand] | visit {player}',
      source_file = 'data/help/inn.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- magic: Magic: Spells, Circles and Chants
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'magic' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'magic' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['magic', 'spellcasting', 'circles', 'spell-circles', 'slots', 'mana']::text[],
      'Magic: Spells, Circles and Chants',
      $help$There is no mana. Magic works on spell slots sorted into circles. A circle
is a tier of power: circle 1 is the weakest, higher circles hold stronger
spells and unlock as you level. Your class and level decide how many slots
you have in each circle.

SEE WHAT YOU HAVE
  spells             the spells you know, grouped by circle
  spells 3           only circle 3          spells 1-2   circles 1 to 2
  spells 2-3 fire    circles 2 and 3 matching "fire"
  spells all         the whole catalog
  slots              free and total slots per circle, and which are
                     recovering. Cooldowns survive logging out.

LEARN
  study {spell}      add a spell from your class list to what you know.
  practice {spell}   raise your proficiency at a trainer (see SKILL).

CAST
  cast fireball goblin       cast at a target; partial names work
  cast 'magic missile' orc   put multi-word names in quotes
  chant {chant} [target]     chants, used by some classes (list: chants)
  perform {song} [target]    songs, used by bards (list: songs)

  Casting takes a few seconds ("You begin casting... about 3s"). "abort"
  stops a cast in progress. A cast uses one slot of the spell's circle and
  starts that circle's recovery timer. You can't cast a spell you haven't
  learned or practiced, one above your level, or one your class lacks. It
  fizzles in rooms where magic doesn't work.

SLOT RECOVERY
  Slots come back by themselves, faster while resting, sleeping or
  sitting, and fastest while you "meditate" or "concentrate".
  (The old commands memorize and forget just show your slots.)

OTHER USEFUL COMMANDS
  recite {scroll} [target]   read a scroll, casting what is written on it
  scribe 'spell name'        write a spell you know (50 percent or better)
                             onto a blank scroll; sit down, out of combat
  effects                    what is affecting you now
  cancel [effect]            list, or drop, a buff you don't want
  cooldowns                  abilities still recharging
  help {spell}               description, cast time and class access

See also: SKILL, GROUPS.$help$,
      0,
      'guide',
      'cast {spell} [target] | chant {chant} [target] | perform {song} | spells | slots',
      'data/help/magic.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['magic', 'spellcasting', 'circles', 'spell-circles', 'slots', 'mana']::text[],
      title = 'Magic: Spells, Circles and Chants',
      content = $help$There is no mana. Magic works on spell slots sorted into circles. A circle
is a tier of power: circle 1 is the weakest, higher circles hold stronger
spells and unlock as you level. Your class and level decide how many slots
you have in each circle.

SEE WHAT YOU HAVE
  spells             the spells you know, grouped by circle
  spells 3           only circle 3          spells 1-2   circles 1 to 2
  spells 2-3 fire    circles 2 and 3 matching "fire"
  spells all         the whole catalog
  slots              free and total slots per circle, and which are
                     recovering. Cooldowns survive logging out.

LEARN
  study {spell}      add a spell from your class list to what you know.
  practice {spell}   raise your proficiency at a trainer (see SKILL).

CAST
  cast fireball goblin       cast at a target; partial names work
  cast 'magic missile' orc   put multi-word names in quotes
  chant {chant} [target]     chants, used by some classes (list: chants)
  perform {song} [target]    songs, used by bards (list: songs)

  Casting takes a few seconds ("You begin casting... about 3s"). "abort"
  stops a cast in progress. A cast uses one slot of the spell's circle and
  starts that circle's recovery timer. You can't cast a spell you haven't
  learned or practiced, one above your level, or one your class lacks. It
  fizzles in rooms where magic doesn't work.

SLOT RECOVERY
  Slots come back by themselves, faster while resting, sleeping or
  sitting, and fastest while you "meditate" or "concentrate".
  (The old commands memorize and forget just show your slots.)

OTHER USEFUL COMMANDS
  recite {scroll} [target]   read a scroll, casting what is written on it
  scribe 'spell name'        write a spell you know (50 percent or better)
                             onto a blank scroll; sit down, out of combat
  effects                    what is affecting you now
  cancel [effect]            list, or drop, a buff you don't want
  cooldowns                  abilities still recharging
  help {spell}               description, cast time and class access

See also: SKILL, GROUPS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'cast {spell} [target] | chant {chant} [target] | perform {song} | spells | slots',
      source_file = 'data/help/magic.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- mail: Mail
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'mail' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'mail' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['mail', 'mailbox', 'postmaster', 'post office', 'readmail', 'delmail', 'check', 'receive']::text[],
      'Mail',
      $help$Mail lets you leave private messages for players who are offline. Mail goes
to the website account behind a character, so every character on that
account shares one inbox.

SENDING (post office only)
  mail Gandalf       start a letter to the account that owns Gandalf.
                     You must be in the same room as a postmaster.

  The first line you type is the subject; the lines after it are the body.
  Type these on a line by themselves:
    .preview   show the letter so far
    .send      send it
    .clear     wipe it and start over
    .abort     cancel

READING (anywhere)
  mailbox            list your messages, newest first. An asterisk marks
                     unread ones. (Also "check".)
  readmail 2         read message 2; it is then marked read.
                     (Also "receive" and "getmail".)
  delmail 2          delete message 2 for good.

  The numbers are the slot numbers shown by mailbox, and they change when
  you delete something, so check mailbox again before deleting.

See also: BOARDS (public messages), CHANNELS (tell).$help$,
      0,
      'guide',
      'mail {character} | mailbox | readmail {#} | delmail {#}',
      'data/help/mail.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['mail', 'mailbox', 'postmaster', 'post office', 'readmail', 'delmail', 'check', 'receive']::text[],
      title = 'Mail',
      content = $help$Mail lets you leave private messages for players who are offline. Mail goes
to the website account behind a character, so every character on that
account shares one inbox.

SENDING (post office only)
  mail Gandalf       start a letter to the account that owns Gandalf.
                     You must be in the same room as a postmaster.

  The first line you type is the subject; the lines after it are the body.
  Type these on a line by themselves:
    .preview   show the letter so far
    .send      send it
    .clear     wipe it and start over
    .abort     cancel

READING (anywhere)
  mailbox            list your messages, newest first. An asterisk marks
                     unread ones. (Also "check".)
  readmail 2         read message 2; it is then marked read.
                     (Also "receive" and "getmail".)
  delmail 2          delete message 2 for good.

  The numbers are the slot numbers shown by mailbox, and they change when
  you delete something, so check mailbox again before deleting.

See also: BOARDS (public messages), CHANNELS (tell).$help$,
      min_level = 0,
      category = 'guide',
      usage = 'mail {character} | mailbox | readmail {#} | delmail {#}',
      source_file = 'data/help/mail.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- newbie: Getting Started
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'newbie' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'newbie' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['newbie', 'start', 'getting-started', 'new-player', 'beginner', 'tutorial', 'first-steps']::text[],
      'Getting Started',
      $help$Welcome to FieryMUD. These are the first steps for a new character. Type
"help {topic}" for details on anything named here.

LOOK AROUND
  look               describe the room         exits    list the exits
  north (n), south (s), east (e), west (w), up (u), down (d) move you.
  scan               peek at the rooms next to you.
  score              your stats       inventory (i)    what you carry
  equipment (eq)     what you wear    wealth           your coin

GEAR UP
  wear {item}, wield {weapon}, remove {item}, get, drop, give.
  A badly dressed character takes far more damage. Shops sell gear:
  see SHOPS.

LEARN YOUR CLASS
  skills, spells and practice show what you can do. Trainers (NPCs) teach
  you and spend the practice points you earn by levelling. See SKILL and
  MAGIC. "where {name}" can help you find someone.

FIGHT SMART
  consider {target}  tells you how dangerous something is. Try it first.
  kill {target}      start a fight.          flee    run away.
  wimpy 30           flee automatically below 30 percent HP.
  rest, sleep and food and drink recover HP and stamina; "stand" gets you
  up. Check hunger and thirst on score.

STAY SAFE
  Touch a touchstone in a safe place, and "recall" will take you back to
  it from anywhere. Keep spare coin in the BANK.

PLAY WITH OTHERS
  GROUPS, CHANNELS (gossip, tell), CLANS, BOARDS and MAIL. Quests are
  listed with "quests"; see QUESTS.

SETTINGS AND ACCOUNT
  PROMPT, color, brief, alias. For passwords, the website and the
  "code" login, see WEBSITE.

Lost? "commands" lists every command, and "help" with no topic shows the
index.$help$,
      0,
      'guide',
      'newbie',
      'data/help/newbie.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['newbie', 'start', 'getting-started', 'new-player', 'beginner', 'tutorial', 'first-steps']::text[],
      title = 'Getting Started',
      content = $help$Welcome to FieryMUD. These are the first steps for a new character. Type
"help {topic}" for details on anything named here.

LOOK AROUND
  look               describe the room         exits    list the exits
  north (n), south (s), east (e), west (w), up (u), down (d) move you.
  scan               peek at the rooms next to you.
  score              your stats       inventory (i)    what you carry
  equipment (eq)     what you wear    wealth           your coin

GEAR UP
  wear {item}, wield {weapon}, remove {item}, get, drop, give.
  A badly dressed character takes far more damage. Shops sell gear:
  see SHOPS.

LEARN YOUR CLASS
  skills, spells and practice show what you can do. Trainers (NPCs) teach
  you and spend the practice points you earn by levelling. See SKILL and
  MAGIC. "where {name}" can help you find someone.

FIGHT SMART
  consider {target}  tells you how dangerous something is. Try it first.
  kill {target}      start a fight.          flee    run away.
  wimpy 30           flee automatically below 30 percent HP.
  rest, sleep and food and drink recover HP and stamina; "stand" gets you
  up. Check hunger and thirst on score.

STAY SAFE
  Touch a touchstone in a safe place, and "recall" will take you back to
  it from anywhere. Keep spare coin in the BANK.

PLAY WITH OTHERS
  GROUPS, CHANNELS (gossip, tell), CLANS, BOARDS and MAIL. Quests are
  listed with "quests"; see QUESTS.

SETTINGS AND ACCOUNT
  PROMPT, color, brief, alias. For passwords, the website and the
  "code" login, see WEBSITE.

Lost? "commands" lists every command, and "help" with no topic shows the
index.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'newbie',
      source_file = 'data/help/newbie.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- prompt: Prompt and Aliases
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'prompt' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'prompt' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['prompt', 'prompts', 'unalias', 'shortcuts', 'customizing']::text[],
      'Prompt and Aliases',
      $help$PROMPT
  The prompt is the status line shown after each batch of output.
    prompt                  show your current template
    prompt list             show the ready-made templates
    prompt compact          adopt one by name
    prompt [%h/%H hp %v/%V mv]    or write your own

  Ready-made names: classic, compact, bars, vitals, verbose, location,
  worldclock, combat, minimal.

  Codes you can use in a template:
    %h %H   current and maximum hit points (%h changes colour as you weaken)
    %v %V   current and maximum stamina
    %B %M   a ten-cell bar for HP and for stamina
    %n      your name           %r   the room you are in
    %g      coin you carry, in copper
    %t      game hour           %s   season        %d   day or night
    %N      your opponent's name    %e %E   their HP and maximum HP
    %p      their health in percent     %K   their health bar
    %%      a percent sign
  The opponent codes show a dash when you aren't fighting.

  Also handy: "color" turns colour on or off, "wimpy 30" makes you flee
  automatically below 30 percent HP, "brief" shortens room descriptions,
  and "toggle" or "flags" show your other settings.

ALIASES
  An alias is your own shortcut for a command.
    alias ga get all        typing "ga corpse" now runs "get all corpse"
    alias                   list your aliases
    alias ga                show one
    unalias ga              remove it

  Aliases are saved between sessions. Only the first word you type is
  replaced; anything after it is added to the end. Some command names are
  reserved and can't be aliased.

See also: NEWBIE, CHANNELS.$help$,
      0,
      'guide',
      'prompt [{template}|list] | alias [{name} [{command}]] | unalias {name}',
      'data/help/prompt.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['prompt', 'prompts', 'unalias', 'shortcuts', 'customizing']::text[],
      title = 'Prompt and Aliases',
      content = $help$PROMPT
  The prompt is the status line shown after each batch of output.
    prompt                  show your current template
    prompt list             show the ready-made templates
    prompt compact          adopt one by name
    prompt [%h/%H hp %v/%V mv]    or write your own

  Ready-made names: classic, compact, bars, vitals, verbose, location,
  worldclock, combat, minimal.

  Codes you can use in a template:
    %h %H   current and maximum hit points (%h changes colour as you weaken)
    %v %V   current and maximum stamina
    %B %M   a ten-cell bar for HP and for stamina
    %n      your name           %r   the room you are in
    %g      coin you carry, in copper
    %t      game hour           %s   season        %d   day or night
    %N      your opponent's name    %e %E   their HP and maximum HP
    %p      their health in percent     %K   their health bar
    %%      a percent sign
  The opponent codes show a dash when you aren't fighting.

  Also handy: "color" turns colour on or off, "wimpy 30" makes you flee
  automatically below 30 percent HP, "brief" shortens room descriptions,
  and "toggle" or "flags" show your other settings.

ALIASES
  An alias is your own shortcut for a command.
    alias ga get all        typing "ga corpse" now runs "get all corpse"
    alias                   list your aliases
    alias ga                show one
    unalias ga              remove it

  Aliases are saved between sessions. Only the first word you type is
  replaced; anything after it is added to the end. Some command names are
  reserved and can't be aliased.

See also: NEWBIE, CHANNELS.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'prompt [{template}|list] | alias [{name} [{command}]] | unalias {name}',
      source_file = 'data/help/prompt.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- quest: Quests
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'quest' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'quest' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['quest', 'quests', 'qaccept', 'questinfo', 'qreward', 'quest-guide']::text[],
      'Quests',
      $help$Quests give you goals and rewards. Most are handed out by creatures and
people you meet in the world.

GETTING A QUEST
  Talk to NPCs with "say" or "ask {mob} {topic}". When you hit a keyword
  they respond to, a conversation starts and may offer you a quest. Some
  quests begin on their own when you reach a level, pick up an item, enter
  a room or use a skill; you are told when that happens. Quests that you
  accept by hand use their zone and id numbers:

    questinfo 30 12    read a quest's level range, flags and description
    qaccept 30 12      accept it

  qaccept refuses if your level is outside the quest's range, a required
  quest is unfinished, you already have it (or finished a quest that can't
  be repeated), it is on cooldown, or it conflicts with another quest you
  hold from the same exclusive group.

TRACKING PROGRESS
  quests             (also qstat, qlist, questlog) list your quests.
                     In-progress quests come first, with their phases and
                     objectives. An arrow marks your current phase and a
                     check mark a finished one; counters such as [2/5]
                     show how far along an objective is. Completed and
                     abandoned quests are listed below.
  abandon {#}        drop an in-progress quest. The number is its position
                     in the in-progress list. It is kept in your history
                     as abandoned.

  Progress is counted automatically as you kill, collect, visit or talk
  to whatever an objective asks for.

REWARDS
  When the last objective is done the quest completes and its fixed rewards
  are granted. Some quests offer a choice (one pick per group):

    qreward                    list choices you haven't claimed yet
    qreward 30 12              list the choices for one quest
    qreward 30 12 7            claim reward number 7 from that list

See also: BOARDS (quest board), CHANNELS (qsay), GROUPS, NEWBIE.$help$,
      0,
      'guide',
      'quests | questinfo {zone} {id} | qaccept {zone} {id} | abandon {#} | qreward',
      'data/help/quests.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['quest', 'quests', 'qaccept', 'questinfo', 'qreward', 'quest-guide']::text[],
      title = 'Quests',
      content = $help$Quests give you goals and rewards. Most are handed out by creatures and
people you meet in the world.

GETTING A QUEST
  Talk to NPCs with "say" or "ask {mob} {topic}". When you hit a keyword
  they respond to, a conversation starts and may offer you a quest. Some
  quests begin on their own when you reach a level, pick up an item, enter
  a room or use a skill; you are told when that happens. Quests that you
  accept by hand use their zone and id numbers:

    questinfo 30 12    read a quest's level range, flags and description
    qaccept 30 12      accept it

  qaccept refuses if your level is outside the quest's range, a required
  quest is unfinished, you already have it (or finished a quest that can't
  be repeated), it is on cooldown, or it conflicts with another quest you
  hold from the same exclusive group.

TRACKING PROGRESS
  quests             (also qstat, qlist, questlog) list your quests.
                     In-progress quests come first, with their phases and
                     objectives. An arrow marks your current phase and a
                     check mark a finished one; counters such as [2/5]
                     show how far along an objective is. Completed and
                     abandoned quests are listed below.
  abandon {#}        drop an in-progress quest. The number is its position
                     in the in-progress list. It is kept in your history
                     as abandoned.

  Progress is counted automatically as you kill, collect, visit or talk
  to whatever an objective asks for.

REWARDS
  When the last objective is done the quest completes and its fixed rewards
  are granted. Some quests offer a choice (one pick per group):

    qreward                    list choices you haven't claimed yet
    qreward 30 12              list the choices for one quest
    qreward 30 12 7            claim reward number 7 from that list

See also: BOARDS (quest board), CHANNELS (qsay), GROUPS, NEWBIE.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'quests | questinfo {zone} {id} | qaccept {zone} {id} | abandon {#} | qreward',
      source_file = 'data/help/quests.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- shops: Shops
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'shops' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'shops' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['shops', 'shop', 'shopping', 'shopkeeper', 'appraise']::text[],
      'Shops',
      $help$Shops are run by shopkeeper NPCs. Stand in the same room as the keeper.

  list              show what the keeper sells: item number, name, price
                    and stock ("unlimited" or a count)
  buy 3             buy item number 3 from the list
  buy dagger        buy by a word from the item's name
  sell sword        sell something you are carrying
  value sword       show an item's base value, weight and minimum level
                    (it searches your inventory and the room)

  Coins come out of, and go into, the coin you carry (see "wealth").
  Anything you can't afford is refused with the amount you are short.
  Keepers pay only a fraction of an item's base value, refuse items
  they don't deal in and anything worthless, and won't buy soulbound
  items. Selling works on what you carry, so remove worn gear first.

PET SHOPS
  Some keepers also have pets for hire. "list" shows them in a second
  table. "hire {#|name}" buys one; it becomes your follower and is named
  after you, for example "Strider's pony".

REPAIRS
  "repair {item}" asks a shopkeeper to refill a lantern or torch for
  10 copper per missing game-hour of fuel. Other items don't wear out.

COINS
  10 copper = 1 silver, 10 silver = 1 gold, 10 gold = 1 platinum.
  Prices are shown broken into those coins.

See also: BANK, GROUPS (split), GETTING-STARTED.$help$,
      0,
      'guide',
      'list | buy {#|name} | sell {item} | value {item} | hire {#|name}',
      'data/help/shops.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['shops', 'shop', 'shopping', 'shopkeeper', 'appraise']::text[],
      title = 'Shops',
      content = $help$Shops are run by shopkeeper NPCs. Stand in the same room as the keeper.

  list              show what the keeper sells: item number, name, price
                    and stock ("unlimited" or a count)
  buy 3             buy item number 3 from the list
  buy dagger        buy by a word from the item's name
  sell sword        sell something you are carrying
  value sword       show an item's base value, weight and minimum level
                    (it searches your inventory and the room)

  Coins come out of, and go into, the coin you carry (see "wealth").
  Anything you can't afford is refused with the amount you are short.
  Keepers pay only a fraction of an item's base value, refuse items
  they don't deal in and anything worthless, and won't buy soulbound
  items. Selling works on what you carry, so remove worn gear first.

PET SHOPS
  Some keepers also have pets for hire. "list" shows them in a second
  table. "hire {#|name}" buys one; it becomes your follower and is named
  after you, for example "Strider's pony".

REPAIRS
  "repair {item}" asks a shopkeeper to refill a lantern or torch for
  10 copper per missing game-hour of fuel. Other items don't wear out.

COINS
  10 copper = 1 silver, 10 silver = 1 gold, 10 gold = 1 platinum.
  Prices are shown broken into those coins.

See also: BANK, GROUPS (split), GETTING-STARTED.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'list | buy {#|name} | sell {item} | value {item} | hire {#|name}',
      source_file = 'data/help/shops.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- skill: Skills, Practice and Training
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'skill' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'skill' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['skill', 'skills', 'practice', 'practise', 'train', 'training', 'proficiency']::text[],
      'Skills, Practice and Training',
      $help$Your class gives you abilities; your proficiency decides how well you use
them. Abilities are spells, skills, chants and songs.

LISTS
  skills             skills you know       skills all   every skill
  spells / chants / songs   the same, for the other kinds
  innate             abilities your race gives you
  practice           everything you know, with proficiency shown as a
                     percentage and a rank: novice, apprentice, skilled,
                     expert, master. A star marks one you are still
                     learning. It also shows your practice points and, for
                     most abilities, the highest your class allows.

PRACTICE POINTS
  You earn practice points by gaining levels. Spend them with a trainer
  (a trainer or guildmaster NPC in the room):

    practice fireball    spend 1 point: proficiency goes up by 5, up to
                         your class's limit for that ability
    train                list your six stats and your points
    train str            spend 1 point to raise strength by 1

  Abilities have to be learned first ("study {spell}" for spells). If
  practice says an ability isn't on your class's list, your class can't
  improve it this way. Stats stop rising at 18, or at your race's own
  maximum if that is lower. The stats are str, dex, con, int, wis, cha.

  Listing with no argument works anywhere; spending a point needs a
  trainer.

Skills you know are also used by name, like kick or backstab; "help
{skill}" explains each one.

See also: MAGIC, NEWBIE.$help$,
      0,
      'guide',
      'skills | practice [{ability}] | train [{stat}] | innate',
      'data/help/skills.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['skill', 'skills', 'practice', 'practise', 'train', 'training', 'proficiency']::text[],
      title = 'Skills, Practice and Training',
      content = $help$Your class gives you abilities; your proficiency decides how well you use
them. Abilities are spells, skills, chants and songs.

LISTS
  skills             skills you know       skills all   every skill
  spells / chants / songs   the same, for the other kinds
  innate             abilities your race gives you
  practice           everything you know, with proficiency shown as a
                     percentage and a rank: novice, apprentice, skilled,
                     expert, master. A star marks one you are still
                     learning. It also shows your practice points and, for
                     most abilities, the highest your class allows.

PRACTICE POINTS
  You earn practice points by gaining levels. Spend them with a trainer
  (a trainer or guildmaster NPC in the room):

    practice fireball    spend 1 point: proficiency goes up by 5, up to
                         your class's limit for that ability
    train                list your six stats and your points
    train str            spend 1 point to raise strength by 1

  Abilities have to be learned first ("study {spell}" for spells). If
  practice says an ability isn't on your class's list, your class can't
  improve it this way. Stats stop rising at 18, or at your race's own
  maximum if that is lower. The stats are str, dex, con, int, wis, cha.

  Listing with no argument works anywhere; spending a point needs a
  trainer.

Skills you know are also used by name, like kick or backstab; "help
{skill}" explains each one.

See also: MAGIC, NEWBIE.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'skills | practice [{ability}] | train [{stat}] | innate',
      source_file = 'data/help/skills.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- website: Website Login, Passwords and Lockout
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'website' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'website' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['website', 'code', 'login', 'password', 'lockout', 'verify', 'device-code', 'tls', 'telnet', 'security']::text[],
      'Website Login, Passwords and Lockout',
      $help$Your characters belong to an account on the FieryMUD website,
https://muditor.fierymud.org. At the login prompt you can give your account
email or a character name.

GAME PASSWORD
  Each character has its own game password. It is separate from your
  website password, and the game never accepts the website password. Set or
  change a character's game password on your website profile page.

LOGGING IN WITHOUT A PASSWORD: THE CODE
  At the "Password:" prompt, type  code  instead of a password.
    1. The game shows an 8-character code and a link, for example
       https://muditor.fierymud.org/verify?code=ABCD-1234
    2. Open it, sign in to the website account that owns the character, and
       approve the code at https://muditor.fierymud.org/verify
    3. Back in the game, press Enter to check. You are logged in.
  The code is valid for about two minutes. Type  cancel  to give up. No
  password is ever sent over the connection, which makes this the safest
  way to log in on an unencrypted link.
  You can ask for up to 5 codes every 10 minutes from one address.
  A character that isn't linked to a website account yet is linked to the
  account that approves the code.

TOO MANY WRONG PASSWORDS
  After several wrong passwords the account is locked for a while (15
  minutes by default) and the game tells you when it will open again.
  While locked, passwords aren't even checked, but there are two ways in:
    - type  code  at the prompt and approve it on the website, or
    - clear the lock from the website.
  Five wrong passwords on one connection also disconnects you.

SECURE CONNECTIONS
  Plain telnet on port 4003 is not encrypted: everything you type,
  including a password, can be read on the way. Connect with TLS on port
  4443 using a client that supports it, or use  code  so no password is
  typed at all.

See also: NEWBIE, MAIL.$help$,
      0,
      'guide',
      'code (typed at the Password prompt)',
      'data/help/website-login.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['website', 'code', 'login', 'password', 'lockout', 'verify', 'device-code', 'tls', 'telnet', 'security']::text[],
      title = 'Website Login, Passwords and Lockout',
      content = $help$Your characters belong to an account on the FieryMUD website,
https://muditor.fierymud.org. At the login prompt you can give your account
email or a character name.

GAME PASSWORD
  Each character has its own game password. It is separate from your
  website password, and the game never accepts the website password. Set or
  change a character's game password on your website profile page.

LOGGING IN WITHOUT A PASSWORD: THE CODE
  At the "Password:" prompt, type  code  instead of a password.
    1. The game shows an 8-character code and a link, for example
       https://muditor.fierymud.org/verify?code=ABCD-1234
    2. Open it, sign in to the website account that owns the character, and
       approve the code at https://muditor.fierymud.org/verify
    3. Back in the game, press Enter to check. You are logged in.
  The code is valid for about two minutes. Type  cancel  to give up. No
  password is ever sent over the connection, which makes this the safest
  way to log in on an unencrypted link.
  You can ask for up to 5 codes every 10 minutes from one address.
  A character that isn't linked to a website account yet is linked to the
  account that approves the code.

TOO MANY WRONG PASSWORDS
  After several wrong passwords the account is locked for a while (15
  minutes by default) and the game tells you when it will open again.
  While locked, passwords aren't even checked, but there are two ways in:
    - type  code  at the prompt and approve it on the website, or
    - clear the lock from the website.
  Five wrong passwords on one connection also disconnects you.

SECURE CONNECTIONS
  Plain telnet on port 4003 is not encrypted: everything you type,
  including a password, can be read on the way. Connect with TLS on port
  4443 using a client that supports it, or use  code  so no password is
  typed at all.

See also: NEWBIE, MAIL.$help$,
      min_level = 0,
      category = 'guide',
      usage = 'code (typed at the Password prompt)',
      source_file = 'data/help/website-login.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;
