-- Authored help guides (generated by `fierylib seed help --emit-sql`).
-- Source: fierylib/data/help/*.md. Do not edit by hand; edit the markdown
-- and regenerate.
-- Idempotent: matches on the primary keyword ("HelpEntry" has no unique key),
-- overwriting a legacy entry with the same primary keyword; re-runs change nothing
-- except updated_at.

-- lua-actor: Lua API: Actor (self, actor)
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-actor' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-actor' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-actor', 'actor', 'self', 'lua actor', 'actor api']::text[],
      'Lua API: Actor (self, actor)',
      $help$self and actor are Actor handles (players and mobs). Unknown fields read as nil
and fields are read-only. tostring(actor) gives "Actor(Name)"; use actor.name.
Methods (return type after ->; none means nothing useful):
  actor:say(msg)  actor:emote(msg)  actor:shout(msg)    room / world speech
  actor:send(msg)                                private line to this actor
  actor:whisper(target_name, msg)                whisper to someone in the room
  actor:command(line)              queue a command; runs after the script ends
  actor:move(direction)            walk through an exit (ignores door state)
  actor:teleport(room)             room is a Room handle
  actor:follow(leader)             leader is an Actor
  actor:damage(n)  actor:heal(n)   change HP (damage stops at 0, heal at max)
  actor:award_exp(n)  actor:save()                  players only
  actor:attack_all()               engage every player in the room
  actor:chant(name, target?, level?)   actor:perform(name, target?, level?)
  actor:breath_attack(element, target?)   cast breathe_<element>
  actor:set_flag(name, on)         mob behaviours: sentinel, stay_zone,
                                   scavenger, wimpy, helper, memory
  actor:has_skill(name) -> bool    actor:has_effect(name) -> bool
  actor:get_has_spell(name) -> bool    spell currently applied
  actor:has_item(zone, id) -> bool     carried or worn
  actor:has_equipped(zone, id) -> bool
  actor:get_worn(slot) -> Object|nil   slot e.g. "wield", "head", "body"
  actor:destroy_item(keyword)      "all.keyword" removes every match
  actor:spawn_object(zone, id) -> Object|nil   into the actor's inventory
  actor:room_name() -> string|nil
  actor:getvar(name) -> any|nil   actor:setvar(name, value)   actor:clearvar(name) -> bool
         persistent per-entity variables; MOBS AND ITEMS ONLY (silent no-op on
         players). Values: string, number, boolean, table; nil clears.
Quest variables (stored on the player):
  actor:get_quest_stage(q) -> int (0 = not started)   actor:start_quest(q)
  actor:advance_quest(q)   actor:complete_quest(q)   actor:fail_quest(q)
  actor:restart_quest(q)   actor:erase_quest(q)
  actor:get_has_completed(q) -> bool   actor:get_has_failed(q) -> bool
  actor:get_quest_var("q:var") -> string ("" when unset)
  actor:set_quest_var(q, var, value) or ("q:var", value)
  actor:active_quest(zone, id) -> Quest|nil, with :getvar(n) :setvar(n, v) :clearvar(n)
Fields: name, alias (first keyword), shortdesc, id, zone_id, level, class,
race, size, gender, title, exp, hp, max_hp (maxhit), alignment, position
(stance): standing/sitting/resting/sleeping/kneeling. Stats: armor, damroll
(attack_power), accuracy, evasion, real_str real_dex real_con real_int
real_wis real_cha. Booleans: is_player, is_mob (is_npc), is_fighting,
is_ghost, is_stunned, is_frozen, can_be_seen. hiddenness (0/1), flags (active
effect names, uppercase, space-separated), room (Room), group_size,
group_member[i] (1 = leader), pronouns possessive/hisher, subjective/heshe,
objective/himher.$help$,
      100,
      'building',
      'actor:method(args) / actor.field',
      'data/help/lua-actor.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-actor', 'actor', 'self', 'lua actor', 'actor api']::text[],
      title = 'Lua API: Actor (self, actor)',
      content = $help$self and actor are Actor handles (players and mobs). Unknown fields read as nil
and fields are read-only. tostring(actor) gives "Actor(Name)"; use actor.name.
Methods (return type after ->; none means nothing useful):
  actor:say(msg)  actor:emote(msg)  actor:shout(msg)    room / world speech
  actor:send(msg)                                private line to this actor
  actor:whisper(target_name, msg)                whisper to someone in the room
  actor:command(line)              queue a command; runs after the script ends
  actor:move(direction)            walk through an exit (ignores door state)
  actor:teleport(room)             room is a Room handle
  actor:follow(leader)             leader is an Actor
  actor:damage(n)  actor:heal(n)   change HP (damage stops at 0, heal at max)
  actor:award_exp(n)  actor:save()                  players only
  actor:attack_all()               engage every player in the room
  actor:chant(name, target?, level?)   actor:perform(name, target?, level?)
  actor:breath_attack(element, target?)   cast breathe_<element>
  actor:set_flag(name, on)         mob behaviours: sentinel, stay_zone,
                                   scavenger, wimpy, helper, memory
  actor:has_skill(name) -> bool    actor:has_effect(name) -> bool
  actor:get_has_spell(name) -> bool    spell currently applied
  actor:has_item(zone, id) -> bool     carried or worn
  actor:has_equipped(zone, id) -> bool
  actor:get_worn(slot) -> Object|nil   slot e.g. "wield", "head", "body"
  actor:destroy_item(keyword)      "all.keyword" removes every match
  actor:spawn_object(zone, id) -> Object|nil   into the actor's inventory
  actor:room_name() -> string|nil
  actor:getvar(name) -> any|nil   actor:setvar(name, value)   actor:clearvar(name) -> bool
         persistent per-entity variables; MOBS AND ITEMS ONLY (silent no-op on
         players). Values: string, number, boolean, table; nil clears.
Quest variables (stored on the player):
  actor:get_quest_stage(q) -> int (0 = not started)   actor:start_quest(q)
  actor:advance_quest(q)   actor:complete_quest(q)   actor:fail_quest(q)
  actor:restart_quest(q)   actor:erase_quest(q)
  actor:get_has_completed(q) -> bool   actor:get_has_failed(q) -> bool
  actor:get_quest_var("q:var") -> string ("" when unset)
  actor:set_quest_var(q, var, value) or ("q:var", value)
  actor:active_quest(zone, id) -> Quest|nil, with :getvar(n) :setvar(n, v) :clearvar(n)
Fields: name, alias (first keyword), shortdesc, id, zone_id, level, class,
race, size, gender, title, exp, hp, max_hp (maxhit), alignment, position
(stance): standing/sitting/resting/sleeping/kneeling. Stats: armor, damroll
(attack_power), accuracy, evasion, real_str real_dex real_con real_int
real_wis real_cha. Booleans: is_player, is_mob (is_npc), is_fighting,
is_ghost, is_stunned, is_frozen, can_be_seen. hiddenness (0/1), flags (active
effect names, uppercase, space-separated), room (Room), group_size,
group_member[i] (1 = leader), pronouns possessive/hisher, subjective/heshe,
objective/himher.$help$,
      min_level = 100,
      category = 'building',
      usage = 'actor:method(args) / actor.field',
      source_file = 'data/help/lua-actor.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- lua-examples: Lua Script Examples
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-examples' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-examples' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-examples', 'lua examples', 'script examples', 'trigger examples']::text[],
      'Lua Script Examples',
      $help$1. Greeting mob (MOB trigger, flag GREET). Greets players only, remembers who
it already welcomed, and throttles with the clock. Ids below are examples.

  if not actor.is_player then return end
  wait(1)
  local last = self:getvar("greeted_" .. actor.name) or 0
  if time.stamp - last < 600 then return end
  self:setvar("greeted_" .. actor.name, time.stamp)
  self:say("Welcome, " .. actor.name .. "!")
  self:command("bow " .. actor.name)

2. Locked-door puzzle (MOB trigger on a gatekeeper, flag RECEIVE). Handing the
guard item (zone 30, id 12) opens the north gate for a while, then it relocks.

  if not (object and object.zone_id == 30 and object.id == 12) then
      self:say("I have no use for that.")
      return
  end
  self:destroy_item("pass")
  local gate = self.room:exit("north")
  if not gate then return end
  gate:set_state{ locked = false, open = true }
  self.room:send(self.name .. " swings the gate open.")
  wait(60)
  gate:set_state{ open = false, locked = true }
  self.room:send("The gate clanks shut and locks.")

3. Timed event (WORLD trigger on a room, flag POSTENTRY). Entering starts a
cave-in after a delay, at most once every two minutes. The timestamp lives in
a room variable, so a restart mid-wait cannot leave the room stuck "armed".

  local room = self.room
  if time.stamp - (room:getvar("last_collapse") or 0) < 120 then return end
  room:setvar("last_collapse", time.stamp)
  room:send("Dust sifts from the ceiling. The walls groan.")
  wait(10)
  room:send("The ceiling collapses!")
  for _, who in ipairs(room.actors) do
      if who.is_player then
          who:damage(20)
          who:send("Falling rock batters you.")
      end
  end

Real scripts to read: fierylib/data/triggers/030/ (e.g. 030_167_calken_greet,
030_33_magistrate_speech_wug). Test with "firetrig <zone> <id>" or the lua
command, and check "scripterrors" afterwards.$help$,
      100,
      'building',
      'attach with Muditor Dashboard > Scripts, then treload',
      'data/help/lua-examples.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-examples', 'lua examples', 'script examples', 'trigger examples']::text[],
      title = 'Lua Script Examples',
      content = $help$1. Greeting mob (MOB trigger, flag GREET). Greets players only, remembers who
it already welcomed, and throttles with the clock. Ids below are examples.

  if not actor.is_player then return end
  wait(1)
  local last = self:getvar("greeted_" .. actor.name) or 0
  if time.stamp - last < 600 then return end
  self:setvar("greeted_" .. actor.name, time.stamp)
  self:say("Welcome, " .. actor.name .. "!")
  self:command("bow " .. actor.name)

2. Locked-door puzzle (MOB trigger on a gatekeeper, flag RECEIVE). Handing the
guard item (zone 30, id 12) opens the north gate for a while, then it relocks.

  if not (object and object.zone_id == 30 and object.id == 12) then
      self:say("I have no use for that.")
      return
  end
  self:destroy_item("pass")
  local gate = self.room:exit("north")
  if not gate then return end
  gate:set_state{ locked = false, open = true }
  self.room:send(self.name .. " swings the gate open.")
  wait(60)
  gate:set_state{ open = false, locked = true }
  self.room:send("The gate clanks shut and locks.")

3. Timed event (WORLD trigger on a room, flag POSTENTRY). Entering starts a
cave-in after a delay, at most once every two minutes. The timestamp lives in
a room variable, so a restart mid-wait cannot leave the room stuck "armed".

  local room = self.room
  if time.stamp - (room:getvar("last_collapse") or 0) < 120 then return end
  room:setvar("last_collapse", time.stamp)
  room:send("Dust sifts from the ceiling. The walls groan.")
  wait(10)
  room:send("The ceiling collapses!")
  for _, who in ipairs(room.actors) do
      if who.is_player then
          who:damage(20)
          who:send("Falling rock batters you.")
      end
  end

Real scripts to read: fierylib/data/triggers/030/ (e.g. 030_167_calken_greet,
030_33_magistrate_speech_wug). Test with "firetrig <zone> <id>" or the lua
command, and check "scripterrors" afterwards.$help$,
      min_level = 100,
      category = 'building',
      usage = 'attach with Muditor Dashboard > Scripts, then treload',
      source_file = 'data/help/lua-examples.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- lua-object: Lua API: Object
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-object' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-object' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-object', 'object', 'item', 'lua object', 'object api']::text[],
      'Lua API: Object',
      $help$Items are the same kind of handle as actors, so everything on "help lua-actor"
exists on them, but only the item-related parts are meaningful. Item handles
come from: self in OBJECT triggers, the object global (RECEIVE only),
actor:get_worn(slot), actor:spawn_object, room:find_object, room:spawn_object.

Fields (read-only; unknown names read as nil):
  object.id, object.zone_id    -> int     prototype id (zone_id, id)
  object.name                  -> string
  object.alias                 -> string  first keyword
  object.shortdesc             -> string  examine text, else the name
  object.level                 -> int
  object.cost                  -> int     base value, copper
  object.type                  -> string  "WEAPON", "ARMOR", ... uppercase
  object.weight                -> number
  object.worn_by               -> Actor|nil   who has it equipped; nil when it is
                                  in a container, on the floor or merely carried
Variables (persistent, saved to the database):
  object:getvar(name) -> any|nil
  object:setvar(name, value)           nil clears
  object:clearvar(name) -> bool

Things you do TO items, from the other handles:
  actor:has_item(zone, id) -> bool         carried or worn
  actor:has_equipped(zone, id) -> bool     worn only
  actor:get_worn(slot) -> Object|nil
  actor:destroy_item(keyword)              "all.keyword" removes every match
  actor:spawn_object(zone, id) -> Object|nil   into inventory
  room:spawn_object(zone, id) -> Object|nil    onto the floor
  room:find_object(keyword) -> Object|nil
  world.destroy(handle)                    delete any item or mob
  world.count_objects(zone, id) -> int     live copies in the world
  objects.template(zone, id) -> Proto      read-only: .id .zone_id .name .shortdesc,
                                           works without spawning

Item events (GET DROP WEAR REMOVE USE CONSUME): self = the item, actor = the
player, object is nil. Use self.id / self.zone_id to identify the item.
RECEIVE on a mob: object = the item handed over.

Example, a cursed ring that drains whoever wears it (OBJECT trigger, flag WEAR):
  local wearer = actor
  wearer:send("The ring tightens painfully around your finger.")
  wearer:damage(5)
  self:setvar("worn_count", (self:getvar("worn_count") or 0) + 1)$help$,
      100,
      'building',
      'object.field / obj:getvar(name)',
      'data/help/lua-object.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-object', 'object', 'item', 'lua object', 'object api']::text[],
      title = 'Lua API: Object',
      content = $help$Items are the same kind of handle as actors, so everything on "help lua-actor"
exists on them, but only the item-related parts are meaningful. Item handles
come from: self in OBJECT triggers, the object global (RECEIVE only),
actor:get_worn(slot), actor:spawn_object, room:find_object, room:spawn_object.

Fields (read-only; unknown names read as nil):
  object.id, object.zone_id    -> int     prototype id (zone_id, id)
  object.name                  -> string
  object.alias                 -> string  first keyword
  object.shortdesc             -> string  examine text, else the name
  object.level                 -> int
  object.cost                  -> int     base value, copper
  object.type                  -> string  "WEAPON", "ARMOR", ... uppercase
  object.weight                -> number
  object.worn_by               -> Actor|nil   who has it equipped; nil when it is
                                  in a container, on the floor or merely carried
Variables (persistent, saved to the database):
  object:getvar(name) -> any|nil
  object:setvar(name, value)           nil clears
  object:clearvar(name) -> bool

Things you do TO items, from the other handles:
  actor:has_item(zone, id) -> bool         carried or worn
  actor:has_equipped(zone, id) -> bool     worn only
  actor:get_worn(slot) -> Object|nil
  actor:destroy_item(keyword)              "all.keyword" removes every match
  actor:spawn_object(zone, id) -> Object|nil   into inventory
  room:spawn_object(zone, id) -> Object|nil    onto the floor
  room:find_object(keyword) -> Object|nil
  world.destroy(handle)                    delete any item or mob
  world.count_objects(zone, id) -> int     live copies in the world
  objects.template(zone, id) -> Proto      read-only: .id .zone_id .name .shortdesc,
                                           works without spawning

Item events (GET DROP WEAR REMOVE USE CONSUME): self = the item, actor = the
player, object is nil. Use self.id / self.zone_id to identify the item.
RECEIVE on a mob: object = the item handed over.

Example, a cursed ring that drains whoever wears it (OBJECT trigger, flag WEAR):
  local wearer = actor
  wearer:send("The ring tightens painfully around your finger.")
  wearer:damage(5)
  self:setvar("worn_count", (self:getvar("worn_count") or 0) + 1)$help$,
      min_level = 100,
      category = 'building',
      usage = 'object.field / obj:getvar(name)',
      source_file = 'data/help/lua-object.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- lua-pitfalls: Lua Pitfalls and Debugging
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-pitfalls' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-pitfalls' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-pitfalls', 'pitfalls', 'lua errors', 'script errors', 'scripterrors', 'debugging']::text[],
      'Lua Pitfalls and Debugging',
      $help$Common mistakes:
  1. Locals in branches. "local x" inside if/elseif is scoped to that branch;
     declare it before the if. Converted DG scripts often get this wrong.
  2. No get.* global. DG "%get.obj_shortdesc[...]%" has no equivalent name; use
     objects.template(zone, id).name or the actor:get_* methods.
  3. No vnum. self.vnum / actor.vnum read as nil without any error. Use
     (zone_id, id): self.zone_id and self.id; objects.template(zone, id).
     Legacy id 3045 is zone 30, id 45.
  4. time.stamp exists here (Unix seconds) and so do hour, minute, day, month,
     year, month_name, season, is_night, is_day. After a wait() the table
     only has stamp, hour, day, month, year. The DG "%time.stamp%" text does
     not work in Lua; write time.stamp.
  5. Unknown fields are nil and fields are read-only: a typo (actor.levl) is
     silent, and "self.hp = 5" raises an error. Use damage() / heal().
  6. get_quest_var returns a string, "" when unset (which is truthy). Compare
     with tonumber(...) or == "".
  7. tostring(actor) is "Actor(Name)". Build commands with actor.name.
  8. In SPEECH fired by "say", actor equals self (the listener); only "ask"
     gives the speaker. Match keywords against the speech global (lowercase).
  9. object is nil except in RECEIVE. In item events self is the item.
 10. setvar / getvar do nothing on players; use quest variables.
 11. In room triggers self is the room: use self.room:send(...).
 12. actor:command runs after the script finishes, not at that line.
 13. Flags with no dispatcher (RANDOM, TIME, ...) never fire. See trigger-types.
 14. wait() scripts die on restart; errors after a wait are not logged.
 15. Output: print() is not shown to players. Do not add \r\n.
 16. Endless loops stop at about 5 million instructions with an "instruction
     budget" error. Always wait() inside loops that poll.

Finding errors:
  scripterrors [<n>]                   newest first, default 20
  GET /api/admin/triggers/errors?limit=N   (admin HTTP, 127.0.0.1:8080)
      -> { total, errors: [ { secs_ago, trigger_zone, trigger_id,
           trigger_name, event, message } ] }, newest first, default 50. The
      log is in memory and also written to the script_error_log table.
      message starts "lua error:" and names the line, for example
      "attempt to index a nil value (field 'x')".
  GET /api/admin/triggers/validate[?zone=N]   compile-checks bodies
  GET /api/admin/triggers/stats               fire counts per event
  tstat <zone> <id>, trighistory <target>     per-trigger / per-entity history
Muditor shows a syntax error and lint warnings in the Scripts editor; fix those
first. Remember "treload" after saving.$help$,
      100,
      'building',
      'scripterrors [<n>]',
      'data/help/lua-pitfalls.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-pitfalls', 'pitfalls', 'lua errors', 'script errors', 'scripterrors', 'debugging']::text[],
      title = 'Lua Pitfalls and Debugging',
      content = $help$Common mistakes:
  1. Locals in branches. "local x" inside if/elseif is scoped to that branch;
     declare it before the if. Converted DG scripts often get this wrong.
  2. No get.* global. DG "%get.obj_shortdesc[...]%" has no equivalent name; use
     objects.template(zone, id).name or the actor:get_* methods.
  3. No vnum. self.vnum / actor.vnum read as nil without any error. Use
     (zone_id, id): self.zone_id and self.id; objects.template(zone, id).
     Legacy id 3045 is zone 30, id 45.
  4. time.stamp exists here (Unix seconds) and so do hour, minute, day, month,
     year, month_name, season, is_night, is_day. After a wait() the table
     only has stamp, hour, day, month, year. The DG "%time.stamp%" text does
     not work in Lua; write time.stamp.
  5. Unknown fields are nil and fields are read-only: a typo (actor.levl) is
     silent, and "self.hp = 5" raises an error. Use damage() / heal().
  6. get_quest_var returns a string, "" when unset (which is truthy). Compare
     with tonumber(...) or == "".
  7. tostring(actor) is "Actor(Name)". Build commands with actor.name.
  8. In SPEECH fired by "say", actor equals self (the listener); only "ask"
     gives the speaker. Match keywords against the speech global (lowercase).
  9. object is nil except in RECEIVE. In item events self is the item.
 10. setvar / getvar do nothing on players; use quest variables.
 11. In room triggers self is the room: use self.room:send(...).
 12. actor:command runs after the script finishes, not at that line.
 13. Flags with no dispatcher (RANDOM, TIME, ...) never fire. See trigger-types.
 14. wait() scripts die on restart; errors after a wait are not logged.
 15. Output: print() is not shown to players. Do not add \r\n.
 16. Endless loops stop at about 5 million instructions with an "instruction
     budget" error. Always wait() inside loops that poll.

Finding errors:
  scripterrors [<n>]                   newest first, default 20
  GET /api/admin/triggers/errors?limit=N   (admin HTTP, 127.0.0.1:8080)
      -> { total, errors: [ { secs_ago, trigger_zone, trigger_id,
           trigger_name, event, message } ] }, newest first, default 50. The
      log is in memory and also written to the script_error_log table.
      message starts "lua error:" and names the line, for example
      "attempt to index a nil value (field 'x')".
  GET /api/admin/triggers/validate[?zone=N]   compile-checks bodies
  GET /api/admin/triggers/stats               fire counts per event
  tstat <zone> <id>, trighistory <target>     per-trigger / per-entity history
Muditor shows a syntax error and lint warnings in the Scripts editor; fix those
first. Remember "treload" after saving.$help$,
      min_level = 100,
      category = 'building',
      usage = 'scripterrors [<n>]',
      source_file = 'data/help/lua-pitfalls.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- lua-room: Lua API: Room
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-room' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-room' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-room', 'room', 'lua room', 'room api']::text[],
      'Lua API: Room',
      $help$Get a Room handle from actor.room (the room an actor stands in), get_room(zone,
id), or self.room inside a WORLD (room) trigger. In a room trigger, self IS the
room, so self.room is the same room; self:send() would not reach players, use
self.room:send().

Methods (return type after ->; none means nothing useful):
  room:send(msg)                      to every player in the room
  room:send_except(actor, msg)        everyone but that actor
  room:send_to_adjacent(msg)          into every room an exit leads to
  room:find_actor(keyword) -> Actor|nil     this room only, substring match
  room:find_object(keyword) -> Object|nil   items on the floor only
  room:spawn_mobile(zone, id) -> Actor|nil  does not fire LOAD
  room:spawn_object(zone, id) -> Object|nil onto the floor
  room:purge()                        remove every mob here (not players/items)
  room:teleport_all(room)             move all actors here to another room
  room:exit(direction) -> Exit|nil    nil when there is no exit that way
  room:at(fn) -> whatever fn returns  just calls fn()
  room:weather() -> string            "clear" if the zone has none
  room:temp() -> string               "mild" if the zone has none
  room:sector() -> string             "FOREST", "CITY", "STRUCTURE", ...
  room:is_outdoor() -> bool
  room:getvar(name) -> any|nil   room:setvar(name, value)   room:clearvar(name) -> bool
          persistent variables; nil clears; value may be string, number,
          boolean or table.

Fields (read-only): room.id (also room.local_id), room.zone_id, room.name,
room.actors (also room.people: 1-based list of Actors, mobs and players),
room.actor_count.

Exit handles (from room:exit("north"); directions: north south east west up
down northeast northwest southeast southwest, short forms n s e w u d ne nw se
sw, plus in and out):
  exit:state() -> "open"|"closed"|"locked"|nil
  exit:hidden() -> bool
  exit:set_state{ open=bool, locked=bool, hidden=bool, description=string,
                  keywords={"gate","door"} }   any subset; locked=true wins
  exit:set_key(zone, id)               object that unlocks it; no args clears
  exit:set_destination(room)           re-target; nil clears

Changing an exit changes only this room's side. For a two-way door, also change
the exit from the room on the other side (get_room(zone, id):exit("south")).

Example:
  local gate = get_room(30, 12):exit("north")
  if gate and gate:state() == "locked" then
      gate:set_state{ locked = false, open = true }
  end$help$,
      100,
      'building',
      'get_room(zone, id) / actor.room / room:method(args)',
      'data/help/lua-room.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-room', 'room', 'lua room', 'room api']::text[],
      title = 'Lua API: Room',
      content = $help$Get a Room handle from actor.room (the room an actor stands in), get_room(zone,
id), or self.room inside a WORLD (room) trigger. In a room trigger, self IS the
room, so self.room is the same room; self:send() would not reach players, use
self.room:send().

Methods (return type after ->; none means nothing useful):
  room:send(msg)                      to every player in the room
  room:send_except(actor, msg)        everyone but that actor
  room:send_to_adjacent(msg)          into every room an exit leads to
  room:find_actor(keyword) -> Actor|nil     this room only, substring match
  room:find_object(keyword) -> Object|nil   items on the floor only
  room:spawn_mobile(zone, id) -> Actor|nil  does not fire LOAD
  room:spawn_object(zone, id) -> Object|nil onto the floor
  room:purge()                        remove every mob here (not players/items)
  room:teleport_all(room)             move all actors here to another room
  room:exit(direction) -> Exit|nil    nil when there is no exit that way
  room:at(fn) -> whatever fn returns  just calls fn()
  room:weather() -> string            "clear" if the zone has none
  room:temp() -> string               "mild" if the zone has none
  room:sector() -> string             "FOREST", "CITY", "STRUCTURE", ...
  room:is_outdoor() -> bool
  room:getvar(name) -> any|nil   room:setvar(name, value)   room:clearvar(name) -> bool
          persistent variables; nil clears; value may be string, number,
          boolean or table.

Fields (read-only): room.id (also room.local_id), room.zone_id, room.name,
room.actors (also room.people: 1-based list of Actors, mobs and players),
room.actor_count.

Exit handles (from room:exit("north"); directions: north south east west up
down northeast northwest southeast southwest, short forms n s e w u d ne nw se
sw, plus in and out):
  exit:state() -> "open"|"closed"|"locked"|nil
  exit:hidden() -> bool
  exit:set_state{ open=bool, locked=bool, hidden=bool, description=string,
                  keywords={"gate","door"} }   any subset; locked=true wins
  exit:set_key(zone, id)               object that unlocks it; no args clears
  exit:set_destination(room)           re-target; nil clears

Changing an exit changes only this room's side. For a two-way door, also change
the exit from the room on the other side (get_room(zone, id):exit("south")).

Example:
  local gate = get_room(30, 12):exit("north")
  if gate and gate:state() == "locked" then
      gate:set_state{ locked = false, open = true }
  end$help$,
      min_level = 100,
      category = 'building',
      usage = 'get_room(zone, id) / actor.room / room:method(args)',
      source_file = 'data/help/lua-room.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- lua-world: Lua API: World and Global Functions
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'lua-world' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'lua-world' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['lua-world', 'world', 'lua globals', 'globals', 'lua functions']::text[],
      'Lua API: World and Global Functions',
      $help$Globals every trigger can use (return type after ->):
  get_room(zone, id) -> Room|nil
  find_actor(keyword) -> Actor|nil      whole world, first match; keyword is a
                                        case-insensitive substring of name/keywords
  random(low, high) -> int              inclusive; use this, not math.random
  percent_chance(n) -> bool             true n percent of the time
  wait(seconds)                         pause the script, then continue (>= 1)
  wait_until(hour, minute)              pause until that game time (minute optional)
  run_room_trigger(zone, id)            run every trigger on that room; deferred
                                        to after the current script finishes
  print(...)                            captured, NOT shown to players here;
                                        use actor:send / room:send instead
  globals                               scratch table, empty on every fire
World queries (namespace "world"):
  world.count_mobiles(zone, id) -> int  world.count_objects(zone, id) -> int
  world.find_mobile(zone, id) -> Actor|nil
  world.destroy(handle)                 despawn a mob or item
Prototypes (no spawn): mobiles.template(zone, id), objects.template(zone, id)
  -> read-only Proto with .id .zone_id .name .shortdesc
Combat (self is the fighter): combat.engage(target)   combat.rescue(victim)
Abilities:
  skills.set_level(actor, name, level)    grant or set a skill
  skills.execute(caster, name, target?)   target is an Actor or a name string
  spells.cast(caster, name, target?, level?)
  Effect.Name                             constant for has_effect, e.g.
                                          actor:has_effect(Effect.Sanctuary)
Clock (namespace "time", read-only snapshot taken when the script starts):
  time.stamp          Unix seconds (use for throttling: now - last > 5)
  time.hour 0-23, time.minute, time.day, time.month, time.year
  time.month_name, time.season, time.is_night, time.is_day
  One game hour is about 75 real seconds.
Event globals (strings): speech (SPEECH, lowercased), cmd and args (COMMAND).
Lua standard libraries: string, table, math, utf8, coroutine (read-only copies),
plus pairs, ipairs, tostring, tonumber, type, select, pcall, error, assert.
Removed: os, io, debug, package, require, load, loadstring, loadfile, dofile.
Limits: about 5 million instructions per run, 64 MB memory.
Persistent variables: obj:setvar / getvar / clearvar on mobs, items and rooms;
quest variables on players (see help lua-actor). Mob and item variables are
saved to the database about every 10 seconds.
Timing: wait(n) is real seconds. A script parked in wait() is lost on server
restart, and errors raised after a wait are not reported in the error log.
Messages sent from Lua already end with a newline; do not add \r\n.$help$,
      100,
      'building',
      'get_room(zone, id) / find_actor(keyword) / wait(seconds)',
      'data/help/lua-world.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['lua-world', 'world', 'lua globals', 'globals', 'lua functions']::text[],
      title = 'Lua API: World and Global Functions',
      content = $help$Globals every trigger can use (return type after ->):
  get_room(zone, id) -> Room|nil
  find_actor(keyword) -> Actor|nil      whole world, first match; keyword is a
                                        case-insensitive substring of name/keywords
  random(low, high) -> int              inclusive; use this, not math.random
  percent_chance(n) -> bool             true n percent of the time
  wait(seconds)                         pause the script, then continue (>= 1)
  wait_until(hour, minute)              pause until that game time (minute optional)
  run_room_trigger(zone, id)            run every trigger on that room; deferred
                                        to after the current script finishes
  print(...)                            captured, NOT shown to players here;
                                        use actor:send / room:send instead
  globals                               scratch table, empty on every fire
World queries (namespace "world"):
  world.count_mobiles(zone, id) -> int  world.count_objects(zone, id) -> int
  world.find_mobile(zone, id) -> Actor|nil
  world.destroy(handle)                 despawn a mob or item
Prototypes (no spawn): mobiles.template(zone, id), objects.template(zone, id)
  -> read-only Proto with .id .zone_id .name .shortdesc
Combat (self is the fighter): combat.engage(target)   combat.rescue(victim)
Abilities:
  skills.set_level(actor, name, level)    grant or set a skill
  skills.execute(caster, name, target?)   target is an Actor or a name string
  spells.cast(caster, name, target?, level?)
  Effect.Name                             constant for has_effect, e.g.
                                          actor:has_effect(Effect.Sanctuary)
Clock (namespace "time", read-only snapshot taken when the script starts):
  time.stamp          Unix seconds (use for throttling: now - last > 5)
  time.hour 0-23, time.minute, time.day, time.month, time.year
  time.month_name, time.season, time.is_night, time.is_day
  One game hour is about 75 real seconds.
Event globals (strings): speech (SPEECH, lowercased), cmd and args (COMMAND).
Lua standard libraries: string, table, math, utf8, coroutine (read-only copies),
plus pairs, ipairs, tostring, tonumber, type, select, pcall, error, assert.
Removed: os, io, debug, package, require, load, loadstring, loadfile, dofile.
Limits: about 5 million instructions per run, 64 MB memory.
Persistent variables: obj:setvar / getvar / clearvar on mobs, items and rooms;
quest variables on players (see help lua-actor). Mob and item variables are
saved to the database about every 10 seconds.
Timing: wait(n) is real seconds. A script parked in wait() is lost on server
restart, and errors raised after a wait are not reported in the error log.
Messages sent from Lua already end with a newline; do not add \r\n.$help$,
      min_level = 100,
      category = 'building',
      usage = 'get_room(zone, id) / find_actor(keyword) / wait(seconds)',
      source_file = 'data/help/lua-world.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- trigger-types: Trigger Types and Variables
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'trigger-types' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'trigger-types' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['trigger-types', 'trigger types', 'trigger flags', 'flags']::text[],
      'Trigger Types and Variables',
      $help$Flags a trigger can carry, when the server fires them, and what self / actor /
object are. self is always the entity the trigger is attached to.

Fired by the server today:
  LOAD       mob   Mob spawns (boot and respawn). self = actor = the mob.
                   Not fired for mobs made by room:spawn_mobile.
  GREET      mob   A player or mob arrives in the room. self = listener,
  GREET_ALL        actor = arriver. Both flags behave identically.
  SPEECH     mob   Someone uses "say" in the room, or "ask <mob> <topic>".
                   Global speech = the text, lowercased.
                   Via say, actor is the same entity as self (the speaker is
                   not available). Via ask, actor = the asker.
  RECEIVE    mob   A player gives the mob an item. self = mob, actor = giver,
                   object = the item (the only event that sets object).
  COMMAND    mob   A player types any command while in the same room (mob or
                   item triggers; room triggers are not asked). Globals cmd
                   (command word) and args (rest of line). actor = typist.
                   "return false" consumes the command.
  FIGHT      mob   After each combat round while it is a target. self = target,
                   actor = attacker. Throttle with time.stamp.
  ATTACK     mob   A player starts an attack on it. self = target, actor = attacker.
  DEATH      mob   Just before the mob dies. self = actor = the mob.
  GET, DROP, WEAR, REMOVE, USE, CONSUME   object
                   self = the item, actor = the player. object is nil.
  PREENTRY   room  Before movers enter. self = the room, actor = mover.
  POSTENTRY  room  After the mover arrives and GREET ran. Same bindings.

Flag-less: run_room_trigger(zone, id) runs ALL triggers on that room whatever
their flags (self = room). The firetrig command and /api/admin/triggers/fire
also run a body directly.

Defined in the schema but NOT fired by the Rust server (no dispatcher yet):
GLOBAL RANDOM CAST LEAVE TIME ACT ENTRY HIT_PERCENT BRIBE MEMORY DOOR SPEECH_TO
LOOK AUTO DEFEND TIMER GIVE RESET. A trigger carrying only these never runs by
itself; for periodic behaviour use wait() loops started from LOAD, or
run_room_trigger.

Listeners for GREET, SPEECH, COMMAND are things located in the same room that
have triggers (mobs, and items lying on the floor).

Return value: only COMMAND looks at it. "return false" stops the typed
command; anything else lets it continue.$help$,
      100,
      'building',
      'see also: tstat <zone> <id>',
      'data/help/trigger-types.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['trigger-types', 'trigger types', 'trigger flags', 'flags']::text[],
      title = 'Trigger Types and Variables',
      content = $help$Flags a trigger can carry, when the server fires them, and what self / actor /
object are. self is always the entity the trigger is attached to.

Fired by the server today:
  LOAD       mob   Mob spawns (boot and respawn). self = actor = the mob.
                   Not fired for mobs made by room:spawn_mobile.
  GREET      mob   A player or mob arrives in the room. self = listener,
  GREET_ALL        actor = arriver. Both flags behave identically.
  SPEECH     mob   Someone uses "say" in the room, or "ask <mob> <topic>".
                   Global speech = the text, lowercased.
                   Via say, actor is the same entity as self (the speaker is
                   not available). Via ask, actor = the asker.
  RECEIVE    mob   A player gives the mob an item. self = mob, actor = giver,
                   object = the item (the only event that sets object).
  COMMAND    mob   A player types any command while in the same room (mob or
                   item triggers; room triggers are not asked). Globals cmd
                   (command word) and args (rest of line). actor = typist.
                   "return false" consumes the command.
  FIGHT      mob   After each combat round while it is a target. self = target,
                   actor = attacker. Throttle with time.stamp.
  ATTACK     mob   A player starts an attack on it. self = target, actor = attacker.
  DEATH      mob   Just before the mob dies. self = actor = the mob.
  GET, DROP, WEAR, REMOVE, USE, CONSUME   object
                   self = the item, actor = the player. object is nil.
  PREENTRY   room  Before movers enter. self = the room, actor = mover.
  POSTENTRY  room  After the mover arrives and GREET ran. Same bindings.

Flag-less: run_room_trigger(zone, id) runs ALL triggers on that room whatever
their flags (self = room). The firetrig command and /api/admin/triggers/fire
also run a body directly.

Defined in the schema but NOT fired by the Rust server (no dispatcher yet):
GLOBAL RANDOM CAST LEAVE TIME ACT ENTRY HIT_PERCENT BRIBE MEMORY DOOR SPEECH_TO
LOOK AUTO DEFEND TIMER GIVE RESET. A trigger carrying only these never runs by
itself; for periodic behaviour use wait() loops started from LOAD, or
run_room_trigger.

Listeners for GREET, SPEECH, COMMAND are things located in the same room that
have triggers (mobs, and items lying on the floor).

Return value: only COMMAND looks at it. "return false" stops the typed
command; anything else lets it continue.$help$,
      min_level = 100,
      category = 'building',
      usage = 'see also: tstat <zone> <id>',
      source_file = 'data/help/trigger-types.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;

-- triggers: Triggers and Scripts
DO $do$
DECLARE v_id integer;
BEGIN
  SELECT id INTO v_id FROM "HelpEntry" WHERE keywords[1] = 'triggers' ORDER BY id LIMIT 1;
  IF v_id IS NULL THEN
    SELECT id INTO v_id FROM "HelpEntry" WHERE 'triggers' = ANY(keywords) ORDER BY id LIMIT 1;
  END IF;
  IF v_id IS NULL THEN
    INSERT INTO "HelpEntry"
      (keywords, title, content, min_level, category, usage, source_file, updated_at)
    VALUES (
      ARRAY['triggers', 'scripts', 'scripting', 'trigger']::text[],
      'Triggers and Scripts',
      $help$A trigger is a Lua script plus a list of event flags. When something happens to
the entity the trigger is attached to (a mob is greeted, an item is picked up,
a player enters a room), the server runs the script body. Triggers are keyed by
(zone_id, id) like every other world entity.

Each trigger has:
  name        free text, shown in the Scripts list and in error reports
  attach type MOB, OBJECT or WORLD (WORLD triggers attach to rooms)
  flags       the events it fires on (see: help trigger-types)
  arguments   optional comma-separated list (stored, not interpreted by the server)
  body        the Lua source

Attaching: create and edit triggers in Muditor under Dashboard > Scripts (name,
attach type, flags, arguments, Lua editor with linter). A mob or object gets a
trigger through the attachTrigger mutation (MobTriggers / ObjectTriggers rows);
room attachments (RoomTriggers) are created by the fierylib import. A trigger
may be attached to many entities; it keeps one body.

Running and reloading: the server loads the whole trigger catalog from the
database at boot. After editing in Muditor, a Builder runs "treload" in game
(or POST /api/admin/triggers/reload). Body edits then apply to every existing
mob and item at once. Attachment changes apply to rooms immediately but only
reach mobs and objects on their NEXT spawn or respawn.

Each fire runs in its own sandbox: new globals you assign are private to that
fire, and a script is stopped after about 5 million Lua instructions.

Builder commands:
  triggers [here|<name>|<zone> <id>|full]  what is attached where
  tstat <zone> <id>                        flags, body and fire statistics
  trighistory [<target>] [<n>]             recent fires for an entity
  scripterrors [<n>]                       recent failures
  firetrig <zone> <id> [<actor>]           run a trigger by hand
  lua <code>                               run a snippet with actor = you

Related help: trigger-types, lua-actor, lua-room, lua-object, lua-world,
lua-examples, lua-pitfalls.$help$,
      100,
      'building',
      'triggers [here | <name> | <zone> <id> | full]',
      'data/help/triggers.md',
      now()
    );
  ELSE
    UPDATE "HelpEntry" SET
      keywords = ARRAY['triggers', 'scripts', 'scripting', 'trigger']::text[],
      title = 'Triggers and Scripts',
      content = $help$A trigger is a Lua script plus a list of event flags. When something happens to
the entity the trigger is attached to (a mob is greeted, an item is picked up,
a player enters a room), the server runs the script body. Triggers are keyed by
(zone_id, id) like every other world entity.

Each trigger has:
  name        free text, shown in the Scripts list and in error reports
  attach type MOB, OBJECT or WORLD (WORLD triggers attach to rooms)
  flags       the events it fires on (see: help trigger-types)
  arguments   optional comma-separated list (stored, not interpreted by the server)
  body        the Lua source

Attaching: create and edit triggers in Muditor under Dashboard > Scripts (name,
attach type, flags, arguments, Lua editor with linter). A mob or object gets a
trigger through the attachTrigger mutation (MobTriggers / ObjectTriggers rows);
room attachments (RoomTriggers) are created by the fierylib import. A trigger
may be attached to many entities; it keeps one body.

Running and reloading: the server loads the whole trigger catalog from the
database at boot. After editing in Muditor, a Builder runs "treload" in game
(or POST /api/admin/triggers/reload). Body edits then apply to every existing
mob and item at once. Attachment changes apply to rooms immediately but only
reach mobs and objects on their NEXT spawn or respawn.

Each fire runs in its own sandbox: new globals you assign are private to that
fire, and a script is stopped after about 5 million Lua instructions.

Builder commands:
  triggers [here|<name>|<zone> <id>|full]  what is attached where
  tstat <zone> <id>                        flags, body and fire statistics
  trighistory [<target>] [<n>]             recent fires for an entity
  scripterrors [<n>]                       recent failures
  firetrig <zone> <id> [<actor>]           run a trigger by hand
  lua <code>                               run a snippet with actor = you

Related help: trigger-types, lua-actor, lua-room, lua-object, lua-world,
lua-examples, lua-pitfalls.$help$,
      min_level = 100,
      category = 'building',
      usage = 'triggers [here | <name> | <zone> <id> | full]',
      source_file = 'data/help/triggers.md',
      updated_at = now()
    WHERE id = v_id;
  END IF;
END
$do$;
